# Generated by Django 4.0.4 on 2022-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='description',
            new_name='color_description',
        ),
        migrations.RenameField(
            model_name='colors',
            old_name='name',
            new_name='color_name',
        ),
        migrations.AddField(
            model_name='colors',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
