# Generated by Django 4.0.5 on 2022-07-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_products_categories_alter_products_colors_and_more'),
        ('colors', '0002_rename_description_colors_color_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.products'),
        ),
    ]
