# Generated by Django 4.0.4 on 2022-07-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_alter_colors_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color_name',
            field=models.CharField(max_length=10),
        ),
    ]
