# Generated by Django 4.0.5 on 2022-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
