# Generated by Django 4.0.5 on 2022-06-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_categories', '0002_subcategories_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='description',
            new_name='sub_category_description',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='name',
            new_name='sub_category_name',
        ),
    ]
