# Generated by Django 4.0.5 on 2022-06-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_categories', '0003_rename_description_subcategories_sub_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='sub_category_description',
            new_name='sub_categories_description',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='sub_category_name',
            new_name='sub_categories_name',
        ),
    ]
