# Generated by Django 4.0.4 on 2022-07-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_description_categories_category_description_and_more'),
        ('sub_categories', '0004_rename_sub_category_description_subcategories_sub_categories_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='main_category',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
