# Generated by Django 4.0.5 on 2022-07-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_categories_category_name'),
        ('sub_categories', '0005_remove_subcategories_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
