# Generated by Django 4.0.5 on 2022-07-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_categories_category_name'),
        ('sub_categories', '0006_alter_subcategories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
