# Generated by Django 4.0.4 on 2022-06-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
