# Generated by Django 4.0.4 on 2022-06-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='category_name',
        ),
    ]
