# Generated by Django 4.0.5 on 2022-07-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_products_categories_alter_products_colors_and_more'),
        ('categories', '0003_rename_description_categories_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.products'),
        ),
    ]
