# Generated by Django 4.0.4 on 2022-07-05 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_products_categories_alter_products_colors_and_more'),
        ('categories', '0007_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.products'),
        ),
    ]
