# Generated by Django 4.0.4 on 2022-07-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=20),
        ),
    ]
