# Generated by Django 4.0.5 on 2022-06-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_categories', '0001_initial'),
        ('categories', '0001_initial'),
        ('Size', '0001_initial'),
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('sku_number', models.CharField(max_length=10)),
                ('prod_details', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=0)),
                ('Categories', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
                ('Colors', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colors.colors')),
                ('Size', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Size.size')),
                ('sub_categories', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sub_categories.subcategories')),
            ],
        ),
    ]
