# Generated by Django 4.0.4 on 2022-06-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
