# Generated by Django 4.0.5 on 2022-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_products_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Categories',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='products',
            name='Colors',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='products',
            name='Size',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_categories',
            field=models.CharField(max_length=15),
        ),
    ]
