# Generated by Django 4.0.5 on 2022-07-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_products_categories_alter_products_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Categories',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
