# Generated by Django 4.0.5 on 2022-07-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_products_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Categories',
            field=models.CharField(max_length=15),
        ),
    ]
