# Generated by Django 4.0.5 on 2022-07-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Colors',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Size',
            new_name='size',
        ),
    ]
