# Generated by Django 4.0.5 on 2022-07-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_categories_products_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='colors',
            new_name='color',
        ),
    ]
