# Generated by Django 4.0.5 on 2022-07-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_prod_details_products_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
