# Generated by Django 4.0.5 on 2022-07-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0004_alter_colors_color_name'),
        ('sub_categories', '0007_alter_subcategories_category_name'),
        ('categories', '0011_alter_categories_category_description_and_more'),
        ('Size', '0004_alter_size_size_name'),
        ('polls', '0012_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.colors'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Size.size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_categories.subcategories'),
        ),
    ]
