# Generated by Django 4.0.5 on 2022-07-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_products_categories_alter_products_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
