# Generated by Django 4.0.5 on 2022-07-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Size', '0004_alter_size_size_name'),
        ('polls', '0015_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Size.size'),
        ),
    ]
