# Generated by Django 4.0.4 on 2022-07-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_alter_categories_category_description_and_more'),
        ('polls', '0016_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
