# Generated by Django 4.0.4 on 2022-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Size', '0003_alter_size_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(max_length=10),
        ),
    ]
